# Generated by Django 5.2.6 on 2025-09-19 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("images", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="customimage",
            name="description",
            field=models.CharField(
                blank=True, default="", max_length=255, verbose_name="description"
            ),
        ),
    ]
