# Generated by Django 4.2.24 on 2025-09-19 08:34

import django.db.models.deletion
import wagtail.blocks
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("wagtailcore", "0089_log_entry_data_json_null_to_object"),
    ]

    operations = [
        migrations.CreateModel(
            name="NavigationSettings",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "primary_navigation",
                    wagtail.fields.StreamField(
                        [
                            (
                                "link",
                                wagtail.blocks.StructBlock(
                                    [
                                        ("page", wagtail.blocks.PageChooserBlock()),
                                        (
                                            "title",
                                            wagtail.blocks.CharBlock(
                                                help_text="Leave blank to use page's listing title.",
                                                required=False,
                                            ),
                                        ),
                                    ]
                                ),
                            )
                        ],
                        blank=True,
                        help_text="Main site navigation",
                        use_json_field=True,
                    ),
                ),
                (
                    "footer_navigation",
                    wagtail.fields.StreamField(
                        [
                            (
                                "link_section",
                                wagtail.blocks.StructBlock(
                                    [
                                        ("section_heading", wagtail.blocks.CharBlock()),
                                        (
                                            "links",
                                            wagtail.blocks.StreamBlock(
                                                [
                                                    (
                                                        "internal",
                                                        wagtail.blocks.StructBlock(
                                                            [
                                                                (
                                                                    "page",
                                                                    wagtail.blocks.PageChooserBlock(),
                                                                ),
                                                                (
                                                                    "title",
                                                                    wagtail.blocks.CharBlock(
                                                                        help_text="Leave blank to use page's listing title.",
                                                                        required=False,
                                                                    ),
                                                                ),
                                                            ]
                                                        ),
                                                    ),
                                                    (
                                                        "external",
                                                        wagtail.blocks.StructBlock(
                                                            [
                                                                (
                                                                    "link",
                                                                    wagtail.blocks.URLBlock(),
                                                                ),
                                                                (
                                                                    "title",
                                                                    wagtail.blocks.CharBlock(),
                                                                ),
                                                            ]
                                                        ),
                                                    ),
                                                ],
                                                label="Links",
                                                max_num=None,
                                            ),
                                        ),
                                    ]
                                ),
                            )
                        ],
                        blank=True,
                        use_json_field=True,
                    ),
                ),
                (
                    "site",
                    models.OneToOneField(
                        editable=False,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="wagtailcore.site",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
