name: Dependencies

on:
  schedule:
    - cron: '0 2 * * 1'  # Run every Monday at 2 AM
  workflow_dispatch:

jobs:
  update-dependencies:
    name: 📦 Update Dependencies
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Check for outdated packages
        run: |
          pip list --outdated

      - name: Update requirements.txt
        run: |
          pip freeze > requirements-updated.txt
          echo "Updated requirements saved to requirements-updated.txt"

      - name: Upload updated requirements
        uses: actions/upload-artifact@v3
        with:
          name: updated-requirements
          path: requirements-updated.txt
          retention-days: 30

      - name: Create PR if updates available
        if: github.event_name == 'schedule'
        uses: actions/github-script@v6
        with:
          script: |
            const fs = require('fs');
            
            // Check if requirements-updated.txt exists
            if (fs.existsSync('requirements-updated.txt')) {
              const updatedContent = fs.readFileSync('requirements-updated.txt', 'utf8');
              const originalContent = fs.readFileSync('requirements.txt', 'utf8');
              
              if (updatedContent !== originalContent) {
                // Create a new branch
                const branchName = `dependabot/update-${new Date().toISOString().split('T')[0]}`;
                
                // Create PR
                github.rest.pulls.create({
                  owner: context.repo.owner,
                  repo: context.repo.repo,
                  title: '🔧 Automated dependency updates',
                  head: branchName,
                  base: 'develop',
                  body: 'This PR contains automated dependency updates.\n\nPlease review the changes and test thoroughly before merging.'
                });
              }
            }
