name: Build Documentation

on:
  push:
    branches: ["main", "staging"]
    paths:
      - "docs/**"
      - "mkdocs.yml"
      - ".readthedocs.yml"
      - "README.md"
  pull_request:
    branches: ["main", "staging"]
    paths:
      - "docs/**"
      - "mkdocs.yml"
      - ".readthedocs.yml"
      - "README.md"

jobs:
  build-docs:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements-docs.txt

      - name: Build documentation
        run: |
          mkdocs build

      - name: Upload documentation artifacts
        uses: actions/upload-artifact@v3
        with:
          name: documentation
          path: site/
          retention-days: 30

      - name: Deploy to GitHub Pages
        if: github.ref == 'refs/heads/main' && github.event_name == 'push'
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./site
          cname: docs.kni.example.com  # Replace with your domain